### ISSUE TITLE
toolbar_title error u see 

### ISSUE THREAD

**Issue by AbodAndroid** [vansikrishna/Multimager#12]
java.lang.NoSuchFieldError: No static field toolbar_title of type I in class Lcom/vlk/multimager/R$id; or its superclasses (declaration of 'com.vlk.multimager.R$id' appears in /data/app/com.muhtech.Usedmobilemarket-1/split_lib_slice_9_apk.apk)
                                                                                at com.vlk.multimager.activities.GalleryActivity.onCreate(GalleryActivity.java:57)
                                                                                at android.app.Activity.performCreate(Activity.java:6904)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                                at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ryanzulham** [comment]
Same with me

**Comment by bharatsonawane23** [comment]
Change your file name toolbar.xml to any other file name.
