### ISSUE TITLE
Not working in android 4.4.4

### ISSUE THREAD

**Issue by PrafulAnand** [vansikrishna/Multimager#6]
hey i am developing an application where uploading pics from gallery is required.....It is working fine in lollipop and higher versions but when I run my app in kitkat version it gives an error that unable to inflate image button in multimager....
FATAL EXCEPTION: main
                                                                               Process: com.example.prafu.testcoursec, PID: 31850
                                                                               java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.prafu.testcoursec/com.vlk.multimager.activities.MultiCameraActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class ImageButton
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5052)
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
                                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                                Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class ImageButton
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:400)
                                                                                   at com.vlk.multimager.activities.CameraFragment.onCreateView(CameraFragment.java:94)
                                                                                   at android.app.Fragment.performCreateView(Fragment.java:1700)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
                                                                                   at android.app.BackStackRecord.run(BackStackRecord.java:690)
                                                                                   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449)
                                                                                   at android.app.Activity.performStart(Activity.java:5251)
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: android.content.res.Resources$NotFoundException: File res/drawable/action_button_bg.xml from drawable resource ID #0x7f020053
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2139)
                                                                                   at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2062)
                                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                                                   at android.view.View.<init>(View.java:3558)
                                                                                   at android.widget.ImageView.<init>(ImageView.java:123)
                                                                                   at android.widget.ImageButton.<init>(ImageButton.java:87)
                                                                                   at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:60)
                                                                                   at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:56)
                                                                                   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029)
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087)
                                                                                   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                                   at com.vlk.multimager.activities.CameraFragment.onCreateView(CameraFragment.java:94) 
                                                                                   at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                                   at android.app.BackStackRecord.run(BackStackRecord.java:690) 
                                                                                   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449) 
                                                                                   at android.app.Activity.performStart(Activity.java:5251) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                                Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
                                                                                   at android.content.res.TypedArray.getColor(TypedArray.java:327)
                                                                                   at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:970)
                                                                                   at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:939)
                                                                                   at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
                                                                                   at android.content.res.Resources.createFromXml(Resources.java:2515)
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2135)
                                                                                   at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393) 
                                                                                   at android.content.res.Resources.loadDrawable(Resources.java:2062) 
                                                                                   at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                                                                                   at android.view.View.<init>(View.java:3558) 
                                                                                   at android.widget.ImageView.<init>(ImageView.java:123) 
                                                                                   at android.widget.ImageButton.<init>(ImageButton.java:87) 
                                                                                   at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:60) 
                                                                                   at android.support.v7.widget.AppCompatImageButton.<init>(AppCompatImageButton.java:56) 
                                                                                   at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:118) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1029) 
                                                                                   at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1087) 
                                                                                   at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47) 
                                                                                   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                   at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:495) 
                                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:400) 
                                                                                   at com.vlk.multimager.activities.CameraFragment.onCreateView(CameraFragment.java:94) 
                                                                                   at android.app.Fragment.performCreateView(Fragment.java:1700) 
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890) 
                                                                                   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062) 
                                                                                   at android.app.BackStackRecord.run(BackStackRecord.java:690) 
                                                                                   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449) 
                                                                                   at android.app.Activity.performStart(Activity.java:5251) 
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173) 
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249) 
                                                                                   at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                   at android.os.Looper.loop(Looper.java:136) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5052) 
                                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612) 
                                                                                   at dalvik.system.NativeStart.main(Native Method)

**Comment by vansikrishna** [comment]
The exception must be related to the ImageButton rendering on Camera Activity. Tested on 4.2 and 4.4 devices but i am unable to reproduce it. Camera Activity opens well. Unfortunately i do not have a device with 4.4.4 version. Emulator for the same version is not available in Android SDK too. Had to use Genymotion for 4.4.4 version. Its working well there too. 

Please see that you are using the updated version of the library i.e. 1.0.4

**Comment by PrafulAnand** [comment]
sir I am updating the version of the library to 1.0.4 so i am getting this -
error could not find  com.crashlytics.sdk.android:crashlytics:2.6.6 error
how to resolve this

**Comment by vansikrishna** [comment]
Sync the gradle build files and it will be gone. Otherwise add the following to your build.gradle dependencies
compile('com.crashlytics.sdk.android:crashlytics:2.6.6@aar') {
        transitive = true;
    }

**Comment by PrafulAnand** [comment]
in app level??or project level

**Comment by vansikrishna** [comment]
in app level. and by the way, i have removed the usage of Fabric crashlytics for now. You can use the latest version 1.0.5 now

**Comment by PrafulAnand** [comment]
very much thank you sir ......I think the whole isssue which i opened yesterday was based on this  crashanalytics only........relieved now....thanks again..................

**Comment by vansikrishna** [comment]
pleasure is mine..sometimes petty things take most of our time. :)

**Comment by PrafulAnand** [comment]
yup....works like a charm on kitkat ...if any other issues arrive again i would open it.:)thanks again

**Comment by svandana05** [comment]
Its not working also after adding this- 
implementation('com.crashlytics.sdk.android:crashlytics:2.10.1@aar') {
        transitive = true;
    }
to app level gradle file

After selecting images from grid layout its showing blank image and not uploading..

Please check the SS attached-
![WhatsApp Image 2020-05-14 at 3 48 55 PM](https://user-images.githubusercontent.com/49112783/81923194-e257f800-95fa-11ea-9056-45a11a266d1c.jpeg)
